### PR TITLE
feat: widen spacy requirements

### PR DESCRIPTION
**Pull request by cburroughs**
spacy is a large library with many transitive dependencies.  Having a tight bound makes resolving datahub-ingests with wider Python ecosystems difficult.

### CODE REVIEW

**Comment by cburroughs** [comment]
Notes:
 * The old constraint had the odd property of allowing 3.5.0, but not 3.5.1
 * I ran the test for over an hour without error, but they didn't complete.  I'm unsure about the expected runtime.

**Comment by cburroughs** [comment]
*polite bump*

**Review by hsheth2 — APPROVED** [review]
LGTM once CI passes

**Comment by cburroughs** [comment]
Thank you!

**Comment by hsheth2** [comment]
@cburroughs I've cut v0.0.11 - should be available in a few

**Pull request merged**
